### ISSUE TITLE
Figure out who to invite for May call 

### ISSUE THREAD

**Issue by emdupre** [ohbm/OpenScienceDemoCalls#37]
I know that we had decided on a theme for our May call (getting excited for Singapore !), but did we also decide on all of our guests ?

**Comment by KirstieJane** [comment]
Thank you @emdupre!

I think we should have someone from the Trainees SIG (I can send a message to a Michelle to ask) because they’re running a really great mentorship event that I’d like to promote.

The maybe someone from the diversity group to talk about their work?

And Greg and Anisha about the hackathon.

Would also be great to ask one of the local organisers (I’m thinking of the folks in Yeo’s group who have been so helpful) to talk about things to do?

There’s also the comms team? Would it be nice to invite them?

I’m ok with doing a bumper call or try to fit all of them into 30 mins. Or just invite a subset!

What do you think?

**Comment by emdupre** [comment]
That sounds great ! I know that we've already reached out to @gkiar and @akeshavan, and they might also have good recommendations for local organizers. I'd love to see someone from the Trainee SIG, too&mdash; if you could send an email that'd be great !

I might prefer to keep to 30 minutes, especially since we're going to be coordinating so many time zones ! Totally up to you, though 😄

**Comment by KirstieJane** [comment]
Michelle from the Student & Postdoc SIG is in ✨ 

What do you think @emdupre - who's good to invite for the 3rd slot?

@gkiar & @akeshavan - are you both available on 31 May?

**Comment by emdupre** [comment]
If there are recommendations for on-the-ground folks from @gkiar or @akeshavan, that would be great !
